ten = input("Nhập tên của bạn: ")
tuoi = input("Nhập tuổi của bạn: ")
truong = input("Nhập trường của bạn đang học: ")
print("Chào ní", ten)
print("Bạn", tuoi,"tuổi")
print("Bạn đang học",truong,"nè")
